This notebook computes the WIS for the predictions, following the six scoring criteria specified in the repository’s README:

In [1]:
import numpy as np
import pandas as pd
import mosqlient as mosq
from epiweeks import Week
from itertools import product
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings("ignore", category=pd.errors.SettingWithCopyWarning)

In [2]:
from mosqlient.scoring import compute_wis

Load the data:

In [3]:
data = pd.read_csv('/Users/eduardoaraujo/Documents/sprint_data_2025/dengue.csv.gz')
data.date = pd.to_datetime(data.date)
data = data.groupby(['date', 'uf'])[['casos']].sum().reset_index()
data = data.sort_values(by = 'date')
data.head()

         date  uf  casos
0  2010-01-03  AC    760
26 2010-01-03  TO    231
25 2010-01-03  SP   1628
24 2010-01-03  SE      3
23 2010-01-03  SC     10

In [4]:
data.max()

date     2025-07-27 00:00:00
uf                        TO
casos                 159561
dtype: object

In [5]:
Week.fromdate(pd.to_datetime('2025-07-27'))

Week(2025, 31, CDC)

In [6]:
data.uf.unique()

array(['AC', 'TO', 'SP', 'SE', 'SC', 'RS', 'RR', 'RO', 'RJ', 'PR', 'PI',
       'PE', 'PB', 'RN', 'MT', 'PA', 'AM', 'AP', 'BA', 'CE', 'DF', 'AL',
       'GO', 'MA', 'MG', 'MS', 'ES'], dtype=object)

Get the range of the peaks in a three week window centered in the peak:

In [7]:
data_23 = data.loc[(data.date >= Week(2022, 41).startdate().strftime('%Y-%m-%d')) & (data.date <= Week(2023, 40).startdate().strftime('%Y-%m-%d'))] 
data_24 = data.loc[(data.date >= Week(2023, 41).startdate().strftime('%Y-%m-%d')) & (data.date <= Week(2024, 40).startdate().strftime('%Y-%m-%d'))] 
data_25 = data.loc[(data.date >= Week(2024, 41).startdate().strftime('%Y-%m-%d')) & (data.date <= Week(2025, 40).startdate().strftime('%Y-%m-%d'))] 

states = data.uf.unique()
years = [2023, 2024, 2025]
peak_dates = {state: {year: {} for year in years} for state in states}

for state in states:
    
    df_23 = data_23.loc[data_23.uf == state]
    
    peak_date = pd.to_datetime(df_23.loc[df_23.casos == df_23['casos'].max()].date.values[0])

    peak_dates[state][2023]['peak_date'] = peak_date

    df_24 = data_24.loc[data_24.uf == state]
    
    peak_date = pd.to_datetime(df_24.loc[df_24.casos == df_24['casos'].max()].date.values[0])

    peak_dates[state][2024]['peak_date'] = peak_date

    df_25 = data_25.loc[data_25.uf == state]
    
    peak_date = pd.to_datetime(df_25.loc[df_25.casos == df_25['casos'].max()].date.values[0])

    peak_dates[state][2025]['peak_date'] = peak_date

In [8]:
peak_dates

{'AC': {2023: {'peak_date': Timestamp('2023-03-12 00:00:00')},
  2024: {'peak_date': Timestamp('2023-12-10 00:00:00')},
  2025: {'peak_date': Timestamp('2025-02-02 00:00:00')}},
 'TO': {2023: {'peak_date': Timestamp('2023-04-09 00:00:00')},
  2024: {'peak_date': Timestamp('2024-04-14 00:00:00')},
  2025: {'peak_date': Timestamp('2025-05-11 00:00:00')}},
 'SP': {2023: {'peak_date': Timestamp('2023-04-09 00:00:00')},
  2024: {'peak_date': Timestamp('2024-05-05 00:00:00')},
  2025: {'peak_date': Timestamp('2025-03-16 00:00:00')}},
 'SE': {2023: {'peak_date': Timestamp('2023-06-11 00:00:00')},
  2024: {'peak_date': Timestamp('2024-03-31 00:00:00')},
  2025: {'peak_date': Timestamp('2025-06-29 00:00:00')}},
 'SC': {2023: {'peak_date': Timestamp('2023-04-16 00:00:00')},
  2024: {'peak_date': Timestamp('2024-04-07 00:00:00')},
  2025: {'peak_date': Timestamp('2025-04-20 00:00:00')}},
 'RS': {2023: {'peak_date': Timestamp('2023-04-16 00:00:00')},
  2024: {'peak_date': Timestamp('2024-04-14 00:00:00')},
  2025: {'peak_date': Timestamp('2025-04-20 00:00:00')}},
 'RR': {2023: {'peak_date': Timestamp('2023-08-27 00:00:00')},
  2024: {'peak_date': Timestamp('2024-06-09 00:00:00')},
  2025: {'peak_date': Timestamp('2025-07-20 00:00:00')}},
 'RO': {2023: {'peak_date': Timestamp('2023-01-08 00:00:00')},
  2024: {'peak_date': Timestamp('2024-03-03 00:00:00')},
  2025: {'peak_date': Timestamp('2025-05-11 00:00:00')}},
 'RJ': {2023: {'peak_date': Timestamp('2023-04-09 00:00:00')},
  2024: {'peak_date': Timestamp('2024-02-18 00:00:00')},
  2025: {'peak_date': Timestamp('2025-02-09 00:00:00')}},
 'PR': {2023: {'peak_date': Timestamp('2023-04-09 00:00:00')},
  2024: {'peak_date': Timestamp('2024-03-31 00:00:00')},
  2025: {'peak_date': Timestamp('2025-03-30 00:00:00')}},
 'PI': {2023: {'peak_date': Timestamp('2023-03-26 00:00:00')},
  2024: {'peak_date': Timestamp('2024-03-10 00:00:00')},
  2025: {'peak_date': Timestamp('2025-05-04 00:00:00')}},
 'PE': {2023: {'peak_date': Timestamp('2023-03-26 00:00:00')},
  2024: {'peak_date': Timestamp('2024-03-31 00:00:00')},
  2025: {'peak_date': Timestamp('2025-07-06 00:00:00')}},
 'PB': {2023: {'peak_date': Timestamp('2023-04-09 00:00:00')},
  2024: {'peak_date': Timestamp('2024-03-17 00:00:00')},
  2025: {'peak_date': Timestamp('2025-02-16 00:00:00')}},
 'RN': {2023: {'peak_date': Timestamp('2023-04-09 00:00:00')},
  2024: {'peak_date': Timestamp('2024-03-10 00:00:00')},
  2025: {'peak_date': Timestamp('2025-04-20 00:00:00')}},
 'MT': {2023: {'peak_date': Timestamp('2023-04-09 00:00:00')},
  2024: {'peak_date': Timestamp('2024-04-28 00:00:00')},
  2025: {'peak_date': Timestamp('2025-01-19 00:00:00')}},
 'PA': {2023: {'peak_date': Timestamp('2023-03-19 00:00:00')},
  2024: {'peak_date': Timestamp('2024-02-25 00:00:00')},
  2025: {'peak_date': Timestamp('2025-02-09 00:00:00')}},
 'AM': {2023: {'peak_date': Timestamp('2023-02-05 00:00:00')},
  2024: {'peak_date': Timestamp('2024-01-14 00:00:00')},
  2025: {'peak_date': Timestamp('2025-03-09 00:00:00')}},
 'AP': {2023: {'peak_date': Timestamp('2023-08-27 00:00:00')},
  2024: {'peak_date': Timestamp('2024-02-25 00:00:00')},
  2025: {'peak_date': Timestamp('2025-01-26 00:00:00')}},
 'BA': {2023: {'peak_date': Timestamp('2023-04-30 00:00:00')},
  2024: {'peak_date': Timestamp('2024-03-31 00:00:00')},
  2025: {'peak_date': Timestamp('2025-04-20 00:00:00')}},
 'CE': {2023: {'peak_date': Timestamp('2023-05-07 00:00:00')},
  2024: {'peak_date': Timestamp('2024-04-07 00:00:00')},
  2025: {'peak_date': Timestamp('2025-04-27 00:00:00')}},
 'DF': {2023: {'peak_date': Timestamp('2023-04-09 00:00:00')},
  2024: {'peak_date': Timestamp('2024-02-18 00:00:00')},
  2025: {'peak_date': Timestamp('2024-11-17 00:00:00')}},
 'AL': {2023: {'peak_date': Timestamp('2023-04-09 00:00:00')},
  2024: {'peak_date': Timestamp('2024-07-07 00:00:00')},
  2025: {'peak_date': Timestamp('2025-06-29 00:00:00')}},
 'GO': {2023: {'peak_date': Timestamp('2023-03-19 00:00:00')},
  2024: {'peak_date': Timestamp('2024-03-10 00:00:00')},
  2025: {'peak_date': Timestamp('2025-05-04 00:00:00')}},
 'MA': {2023: {'peak_date': Timestamp('2023-03-05 00:00:00')},
  2024: {'peak_date': Timestamp('2024-03-17 00:00:00')},
  2025: {'peak_date': Timestamp('2025-03-16 00:00:00')}},
 'MG': {2023: {'peak_date': Timestamp('2023-04-09 00:00:00')},
  2024: {'peak_date': Timestamp('2024-03-17 00:00:00')},
  2025: {'peak_date': Timestamp('2025-02-16 00:00:00')}},
 'MS': {2023: {'peak_date': Timestamp('2023-03-26 00:00:00')},
  2024: {'peak_date': Timestamp('2024-03-10 00:00:00')},
  2025: {'peak_date': Timestamp('2025-04-06 00:00:00')}},
 'ES': {2023: {'peak_date': Timestamp('2023-03-26 00:00:00')},
  2024: {'peak_date': Timestamp('2024-03-10 00:00:00')},
  2025: {'peak_date': Timestamp('2024-12-15 00:00:00')}}}

Load predictions:

In [9]:
df_preds = pd.read_csv('predictions/preds_2nd_sprint_update.csv.gz')

df_preds['date'] = pd.to_datetime(df_preds.date)

df_preds['valid_test'] = df_preds['valid_test'].astype(str)

df_preds = df_preds.loc[df_preds.valid_test.isin(['1', '2', '3'])]

df_preds.head()

,date,lower_95,lower_90,lower_80,lower_50,pred,upper_50,upper_80,upper_90,upper_95,valid_test,state,model_id
0,2024-10-06,38.773291,47.763807,60.738967,90.734958,141.694291,221.242326,330.372751,419.958960,517.109128,3,PA,108
1,2024-10-13,45.109840,55.739146,71.131107,106.889566,168.026644,264.099302,396.728996,506.114194,625.130454,3,PA,108
2,2024-10-20,41.814331,51.824573,66.367288,100.313705,158.710997,251.070224,379.348800,485.622490,601.625766,3,PA,108
3,2024-10-27,56.360496,70.048836,89.997844,136.779116,217.737829,346.580496,526.586520,676.366250,840.369406,3,PA,108
4,2024-11-03,62.131360,77.438292,99.814751,152.524496,244.274360,391.179445,597.597813,770.084987,959.525955,3,PA,108

In [10]:
df_preds.valid_test.unique()

array(['3', '2', '1'], dtype=object)

In [11]:
df_preds.model_id.unique()

array([108, 133, 134, 135, 136, 137, 138, 143, 144, 145, 150, 152, 154,
       155, 156, 157, 158])

In [12]:
t_ = df_preds.groupby(['valid_test', 'state', 'model_id'])[['pred']].count()

t_.loc[t_.pred != 52]

Empty DataFrame
Columns: [pred]
Index: []

In [13]:
t_ = df_preds.groupby(['date', 'state', 'model_id']).count()
t_.loc[t_.pred > 1]

Empty DataFrame
Columns: [lower_95, lower_90, lower_80, lower_50, pred, upper_50, upper_80, upper_90, upper_95, valid_test]
Index: []

Dataframe with the metrics computed:

In [14]:
def compute_metrics(model, df_w, df_preds_, state=None, year=None, peak = False):
    '''
    Function to compute the score for the entire validation test or only around the peak (if peak=True).
    '''

    if peak: 

        pw = peak_dates[state][2022+int(year)]['peak_date']

        start = Week.fromdate(pw - pd.Timedelta(days = 7)).startdate().strftime('%Y-%m-%d')
    
        end = Week.fromdate(pw + pd.Timedelta(days = 7)).startdate().strftime('%Y-%m-%d')
    
        dates_ =  pd.date_range(start= start,
                  end= end,
                  freq='W-SUN')

        df_preds_2 = df_preds_.loc[df_preds_.date.isin(dates_)]
        df_w2 = df_w.loc[df_w.date.isin(dates_)]
        
    else:
        df_preds_2 = df_preds_
        df_w2 = df_w
        
    df_preds_model = df_preds_2.loc[df_preds_2.model_id == model].reset_index(drop = True)
        
    df_preds_to_score = df_w2.merge(df_preds_model, left_on = ['date', 'uf'], right_on = ['date', 'state'])

    wis = np.mean(compute_wis( 
                        df_preds_to_score[['date',  'lower_95', 'lower_90', 'lower_80', 'lower_50',
                           'pred', 'upper_50', 'upper_80', 'upper_90', 'upper_95']],
                        observed_value = df_preds_to_score['casos'].values)) 
    return wis

In [15]:
%%time
df_metrics = pd.DataFrame()

for state, test_year in product(df_preds.state.unique(), ['1', '2', '3']):
    #print(f'{state} - {test_year}')
    df_preds_ = df_preds.loc[(df_preds.state == state) & (df_preds.valid_test == test_year)].sort_values(by='date')

    df_w = data.loc[(data.uf == state) & data.date.isin(df_preds_.date.unique())].reset_index(drop=True)

    scores =[]
    models_ids = df_preds_.model_id.unique()
    
    for model in models_ids: 
        #print(model)
    
        wis = compute_metrics(model, df_w, df_preds_, state=state, year=test_year, peak = False)
        
        df_metrics = pd.concat([df_metrics,
                           pd.DataFrame([[model, state, test_year, wis ]],
                            columns = ['model', 'state', 'validation_test', 'WIS'] 
                            )], ignore_index = True)


for state in df_preds.state.unique():
    #print(f'{state} - {test_year}')
    df_preds_ = df_preds.loc[(df_preds.state == state)].sort_values(by='date')

    df_w = data.loc[(data.uf == state) & data.date.isin(df_preds_.date.unique())].reset_index(drop=True)

    scores =[]
    models_ids = df_preds_.model_id.unique()
    
    for model in models_ids: 
        #print(model)
    
        wis = compute_metrics(model, df_w, df_preds_, state=state, year=test_year, peak = False)
        
        df_metrics = pd.concat([df_metrics,
                           pd.DataFrame([[model, state, 'all', wis ]],
                            columns = ['model', 'state', 'validation_test', 'WIS'] 
                            )], ignore_index = True)




df_metrics.head()

CPU times: user 2.56 s, sys: 8.38 ms, total: 2.57 s
Wall time: 2.57 s

   model state validation_test        WIS
0    108    PA               1  33.928893
1    138    PA               1  42.055785
2    137    PA               1  63.957493
3    133    PA               1  19.723253
4    158    PA               1  26.092415

In [16]:
df_metrics.validation_test.unique()

array(['1', '2', '3', 'all'], dtype=object)

In [17]:
import warnings

# Turn the RuntimeWarning for empty slices into an exception
warnings.filterwarnings("error", category=RuntimeWarning)

In [18]:
df_metrics_peak = pd.DataFrame()

for state, test_year in product(df_preds.state.unique(), ['1', '2', '3']):
    #print(f'{state} - {test_year}')
    df_preds_ = df_preds.loc[(df_preds.state == state) & (df_preds.valid_test ==test_year)]

    df_w = data.loc[(data.uf == state) & data.date.isin(df_preds_.date.unique())].reset_index(drop=True)
        
    scores =[]
    models_ids = df_preds_.model_id.unique()
    
    for model in models_ids: 
        #print(model)
    
        wis = compute_metrics(model, df_w, df_preds_, state=state, year=test_year, peak = True)
        
        df_metrics_peak = pd.concat([df_metrics_peak,
                           pd.DataFrame([[model, state, test_year, wis ]],
                            columns = ['model', 'state', 'validation_test', 'WIS'] 
                            )], ignore_index = True)

df_metrics_peak.head()

   model state validation_test         WIS
0    108    PA               1   46.612178
1    133    PA               1   44.526901
2    134    PA               1  146.103373
3    135    PA               1   96.776296
4    136    PA               1  142.737693

In [19]:
df_end = df_metrics.merge(df_metrics_peak.rename(columns = {'WIS': 'WIS_peak'}), left_on = ['model', 'state', 'validation_test'], 
                                         right_on = ['model', 'state', 'validation_test'], how = 'outer')

df_end.isnull().sum()

model                0
state                0
validation_test      0
WIS                  0
WIS_peak           454
dtype: int64

In [20]:
df_end.loc[df_end.WIS_peak.isna()].validation_test.unique()

array(['all'], dtype=object)

In [21]:
df_end.to_csv('results/metrics_wis.csv', index = False)